---
Launch School Book: Ruby Basics - Exercises
ExerciseName: [What's My Value? (Part 8)](https://launchschool.com/exercises/e1282eea)
FileName: ex08.md
Answered On: 05/22/2020
---

# What's My Value? (Part 8)

What will the following code print and why? Don't run it until you have 
tried to answer.

```ruby

array = [1, 2, 3]

array.each do |element|
  a = element
end

puts a

```
Output: Error

Explanation: 

This exercise uses array#each method, which is a method invocation with a block.

As array.each iterates through all three values in the array and stopping at the last 
value 3.

Finally the last line `puts a` produces and erorr as it is being called without first
being initialized outside the array.each method and therefore outside the scope.


Key Points: 

1. Method invoication with a block is different than method definition
2. A variable outside a method has a different scope than a variable inside 
a method. Therefor it's possible to share the same variable name and refer to 
different object_id's and output different values if the method is non-destructive.

Resources:

1. [LS Ruby Variable Scope](https://launchschool.com/books/ruby/read/variables#variablescope)
2. [Mutating and Non-Mutating Methods in Ruby](https://launchschool.com/blog/mutating-and-non-mutating-methods)
3. [Mutate The Caller](https://medium.com/@anacasilva/mutate-the-caller-bf01d90c15a6)